### ISSUE TITLE
Création d'un attribut "date"

### ISSUE THREAD

**Issue by funbben** [Eoxia/WPshop-1.y.z#10]
Bonjour,

J'ai créé un attribut date qui a l'air de fonctionner, cependant quand je l'édite, j'obtiens ces messages d'erreur.
J'ai essayer de positionner une limité inférieure et supérieure, mais on dirait quelle ne marche pas.

Warning: Illegal string offset 'attribute_type_date_options_available_date_past_futur' in /var/www/vhosts/cocoricocotte.fr/httpdocs/wp-content/plugins/wpshop/includes/librairies/eav/attributes.class.php on line 2596

Warning: Illegal string offset 'minDate' in /var/www/vhosts/cocoricocotte.fr/httpdocs/wp-content/plugins/wpshop/includes/librairies/eav/attributes.class.php on line 2596

Warning: Illegal string offset 'attribute_type_date_options_available_date_past_futur' in /var/www/vhosts/cocoricocotte.fr/httpdocs/wp-content/plugins/wpshop/includes/librairies/eav/attributes.class.php on line 2602

Warning: Illegal string offset 'maxDate' in /var/www/vhosts/cocoricocotte.fr/httpdocs/wp-content/plugins/wpshop/includes/librairies/eav/attributes.class.php on line 2602

**Comment by lmag** [comment]
Pouvez vous nous notez les versions de WPShop et de WordPress ? Avez vous un lien vers votre site ?

**Comment by lmag** [comment]
Oups, je pense que le site est ligne c'est bien https://cocoricocotte.fr/ ?? 
Il manque la réécriture des urls EX : https://cocoricocotte.fr/?p=253

**Comment by lmag** [comment]
Bonjour,
Le bug est noté sous le numéro 10808. Il sera livré dans la prochaine version de WPShop.
Il est déjà livrée sur Github dans la branche alpha...Si vous voulez le récupérer.
Cependant, ces fonctions risques d'être bientôt déprécier.
