### ISSUE TITLE
Gestion stock par taille

### ISSUE THREAD

**Issue by JimmyBillan** [Eoxia/WPshop-1.y.z#12]
Bonjour,
J'ai constaté que la gestion du stock par taille n'était pas pris en compte, uniquement le stock "global" est décrémenté. 
J'ai vu des postes de 2014 sur votre forum où vous parliez d'une implementation prochaine. 
Est ce que je passe à coté de quelque chose ?

**Comment by lmag** [comment]
Bonjour,
Cela a été fait, le stock est prévu pour chaque variation, cependant nous allons revenir au produit simple dans la livraison de WpShop V2
