### ISSUE TITLE
Product creation bug

### ISSUE THREAD

**Issue by felix-the-real-cat** [Eoxia/WPshop-1.y.z#16]
After a brand new fresh install (WP + WPShop), I try to create a new product and get this error :

Fatal error: Uncaught Error: Cannot use string offset as an array in /path/to/wp-content/plugins/wpshop/includes/librairies/eav/attributes_set.class.php:977 Stack trace: #0 /path/to/wp-content/plugins/wpshop/includes/librairies/eav/attributes.class.php(2243): wpshop_attributes_set::getAttributeSetDetails('1', ''valid','delete...') #1 /path/to/wp-content/plugins/wpshop/includes/librairies/catalog/products.class.php(250): wpshop_attributes::entities_attribute_box('1', 'wpshop_product', 59) #2 /path/to/wp-includes/class-wp-hook.php(288): wpshop_products::add_meta_boxes('wpshop_product') #3 /path/to/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /path/to/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /path/to/wp-admin/e in /path/to/wp-content/plugins/wpshop/includes/librairies/eav/attributes_set.class.php on line 977

**Comment by eman062000** [comment]
Hi, 
Have you find how to fix your bug ??
I have the same..

**Comment by lmag** [comment]
C'est un doublon
