### ISSUE TITLE
Quelle est la licence de wpshop ?

### ISSUE THREAD

**Issue by LudovicRousseau** [Eoxia/WPshop-1.y.z#17]
Vous indiquez : "Wpshop an ecommerce extension 100% free, open source and developed in France."
Je n'ai pas réussi à trouver quelle licence de logiciel libre est utilisée pour wpshop.

Je vous suggère d'utiliser GNU Affero General Public License
https://fr.wikipedia.org/wiki/GNU_Affero_General_Public_License

**Comment by eoxia-jimmy** [comment]
Bonjour,

effectivement ce n'est pas très clair, selon le readme.txt la licence est GPLv2 or later

https://github.com/Eoxia/wpshop/blob/master/readme.txt#L9

Il manque le fichier licence.txt à la racine.

@lmag Suggestion d'une licence AGPL par @LudovicRousseau 

Cordialement,
Jimmy.

**Comment by LudovicRousseau** [comment]
Il faudrait aussi ajouter une entête avec la licence dans chaque fichier source.
Voir https://reuse.software/

**Comment by eoxia-jimmy** [comment]
Bonjour,

Nous devons donc placer à chaque début de fichier: SPDX-License-Identifier: <notre-licence>

Je ne vois aucun plugin WordPress avec cette ligne. 

Je vais continuer à lire la doc https://reuse.software/practices/2.0/

Par exemple même WordPress ne respecte pas cette norme: https://github.com/WordPress/WordPress/blob/master/wp-includes/class-http.php 
Pas de licence défini en haut du fichier.

**Comment by lmag** [comment]
Merci bien pour ta remarque pertinente, on a fait un tour sur certains dépôts pour faire la mise à jour :)
