### ISSUE TITLE
WPShop modifications des étapes d'une commande

### ISSUE THREAD

**Issue by Quentind85** [Eoxia/WPshop-1.y.z#18]
Bonsoir,

Je voudrais modifier les étapes lors d'une commande sur mon site internet, 
Je n'arrive pas à trouver les fichiers qui correspondent aux étapes sur mon FTP

Pouvez-vous m'aider ?

**Comment by lmag** [comment]
Bonjour,
Nous allons bientôt publier la nouvelle version connectable facilement à un ERP (En standard Dolibarr). Vous pourrez ainsi modifier les flux de commandes.

Bien cordialement
