### ISSUE TITLE
Erreur sur l'ajout de nouveau produit

### ISSUE THREAD

**Issue by eman062000** [Eoxia/WPshop-1.y.z#19]
Bonjour / Hi,

Quand j'ajoute un nouveau produit , j'ai cette erreur : / When i add a new product in WPshop there are this error :

WPshop ver. : 1.6.0
Wordpress ver. : 4.9.7 fr
Wamp ver. : 3.1.3
PhP ver. : 7.2.4
MySQL ver. : 5.7.21

( ! ) Fatal error: Uncaught Error: Cannot use string offset as an array in E:\Wamp64\www\wp-content\plugins\wpshop\includes\librairies\eav\attributes_set.class.php on line 977
( ! ) Error: Cannot use string offset as an array in E:\Wamp64\www\wp-content\plugins\wpshop\includes\librairies\eav\attributes_set.class.php on line 977
Call Stack
# Time Memory Function Location
1 0.0002 410064 {main}( ) …\post-new.php:0
2 1.0687 23535952 include( ‘E:\Wamp64\www\wp-admin\edit-form-advanced.php’ ) …\post-new.php:76
3 1.0772 23568192 do_action( ) …\edit-form-advanced.php:334
4 1.0772 23568568 WP_Hook->do_action( ) …\plugin.php:453
5 1.0772 23568568 WP_Hook->apply_filters( ) …\class-wp-hook.php:310
6 1.0788 23592936 wpshop_products::add_meta_boxes( ) …\class-wp-hook.php:288
7 1.0841 23595080 wpshop_attributes::entities_attribute_box( ) …\products.class.php:250
8 1.0841 23595456 wpshop_attributes_set::getAttributeSetDetails( ) …\attributes.class.php:2243

**Comment by albinolet** [comment]
bonjour,

J'ai eu ce problème : éditez le fichier  attributes_set.class.php et ajoutez ligne 975
 975 $attributeSetDetailsGroups = array() ;
cela devrait fonctionner

cordialement.

**Comment by spocky35** [comment]
Bonjour,
je reprends ce sujet, car j'ai la même erreur de départ. J'ai déjà ajouté la ligne 975, mais cela a pour effet de me renvoyer 4 autres messages d'erreur:
- Warning: Illegal string offset 'field' in C:\wamp64\www\WP\wp-content\plugins\wpshop\includes\librairies\eav\attributes.class.php on line 1992

-  Warning: Illegal string offset 'field' in C:\wamp64\www\WP\wp-content\plugins\wpshop\includes\librairies\eav\attributes.class.php on line 2011

- Fatal error: Uncaught Error: Cannot use assign-op operators with string offsets in C:\wamp64\www\WP\wp-content\plugins\wpshop\includes\librairies\eav\attributes.class.php on line 2011

- Error: Cannot use assign-op operators with string offsets in C:\wamp64\www\WP\wp-content\plugins\wpshop\includes\librairies\eav\attributes.class.php on line 2011


Voici ce qui me semble être le bloc de code concerné


`	 * @param array $attribute_list
	 * @param string $output_from
	 * @return string The output for
	 */
	public static function display_attribute( $attribute_code, $output_from = 'admin', $output_specs = array() ) {
		$output = '';
		/*	Get the page code	*/
		$currentPageCode = !empty($output_specs['page_code']) ? $output_specs['page_code'] : '';
		$element_identifier = !empty($output_specs['element_identifier']) ? $output_specs['element_identifier'] : '';

		/*	Get attribute definition	*/
		$attribute_def = wpshop_attributes::getElement($attribute_code, "'valid'", 'code');

		/*	Get attribute input definition	*/
		$current_value = (!empty($output_specs['current_value']) ? $output_specs['current_value'] : '');
		$input = wpshop_attributes::get_attribute_field_definition( $attribute_def, $current_value, array_merge($output_specs, array('input_class' => ' wpshop_attributes_display', 'from' => $output_from)) );

		/*	Create default output	*/
		$input_to_display = $input['output'] . $input['options'];

		/*	Check if current field is linked to an addon, and if the addon is activated	*/
		$addons_list = unserialize(WPSHOP_ADDONS_LIST);
		foreach ( $addons_list as $addon_code => $addon_def ) {
			if ( in_array($attribute_code, $addon_def) ) {
				if ( constant($addon_code) === false ) {
					$input_to_display = '<a href="' . admin_url('options-general.php?page=wpshop_option#wpshop_addons_option') . '" >' . __("This addon isn't activated, click to activate",'wpshop') . '</a>';
				}
			}
		}

		/*	Check the prices attribute because output for this attributes is customized	*/
		$price_tab = unserialize(WPSHOP_ATTRIBUTE_PRICES);
		unset($price_tab[array_search(WPSHOP_COST_OF_POSTAGE, $price_tab)]);

 		$output['field'] = '
<div class="wpshop_cls" >
	<div class="wpshop_form_label ' . $currentPageCode . '_' . $input['name'] . '_label ' . (in_array($attribute_def->code, $price_tab) ? $currentPageCode . '_prices_label ' : '') . ' alignleft" >
		<label ' . $input['label_pointer'] . ' >' . __($input['label'], 'wpshop') . ($attribute_def->is_required == 'yes' ? ' <span class="wpshop_required" >*</span>' : '') . '</label>
	</div>
	<div class="wpshop_form_input_element ' . $currentPageCode . '_' . $input['name'] . '_input ' . (in_array($attribute_def->code, $price_tab) ? $currentPageCode . '_prices_input ' : '') . ' ' . $input['field_container_class'] . ' alignleft" >
		' . $input_to_display . '
	</div>';

// 		$output['field']  = '<div class="wps-form-group wpshop_form_label ' . $currentPageCode . '_' . $input['name'] . '_label ' . (in_array($attribute_def->code, $price_tab) ? $currentPageCode . '_prices_label ' : '') . ' ">';
// 		$output['field'] .= '<label ' . $input['label_pointer'] . '>' . __($input['label'], 'wpshop'). '</label>'.( ($attribute_def->is_required == 'yes') ? '<span class="wps-help-inline wps-help-inline-title">' .__( 'Required variation', 'wpshop' ). '</span>' : '');
// 		$output['field'] .= '<div class="wps-form ' . $currentPageCode . '_' . $input['name'] . '_input ' . (in_array($attribute_def->code, $price_tab) ? $currentPageCode . '_prices_input ' : '') . ' ' . $input['field_container_class'] . ' ">' .$input_to_display. '</div>';

		/*
		 * Display attribute option if applicable
		 */
		if ( $output_from == 'admin') {
			$attribute_option_display = $attribute_def->backend_input=='select' && (strtolower( __(self::get_attribute_type_select_option_info($input['value'], 'value'), 'wpshop') ) == strtolower(__('yes', 'wpshop'))) ? '' : ' wpshopHide';

			$output['field'] = '
	<div class="attribute_option_'.$attribute_def->code.''.$attribute_option_display.'">'.self::get_attribute_option_fields($element_identifier, $attribute_def->code).'</div>';
		}

		$output['field'] .= '</div>';
		$output['field_definition'] = $input;

		return $output;
	}
`

Les lignes incriminées sont  $output['field']=    et     $output['field'].=

Je fais tourner sous wampserver, avec Wordpress 5.0.3 
Quelqu'un aurait une piste?

**Comment by spocky35** [comment]
Je viens de trouver par hasard, en ayant potassé les sujet qui traitent de ce type de message d'erreur. 
Il faut saisir à la ligne 1991 (soit avant la ligne de première erreur
$output = array ();

et tout rentre dans l'ordre.

**Comment by albinolet** [comment]
Salut,

Merci pour l'info
cordialement

**Comment by lmag** [comment]
Bonjour,

Nous allons voir si on peut intégrer la proposition pour la prochaine livraison

**Comment by headmax** [comment]
Je viens de tester la solution de spocky35 qui solutionne mais créer une autre erreur au niveau de l'arborescence du tableau.
J'ai changé part :
		$output = [];
		$output['field'] = '';
J'ai plus aucune erreur, $ouput est bien un tableau mais $output['field'] attends une chaîne de caractère ici du html parsé.
