### ISSUE TITLE
problème de gestion des poids des produits avec option

### ISSUE THREAD

**Issue by Bouillettetarnaise** [Eoxia/WPshop-1.y.z#20]
Bonjour,
j'ai créé un produit pour lequel j'ai plusieurs conditionnements, j'ai donc créé un produit avec option pour que mes clients choisissent le conditionnement (1 kg, 2.5kg, 5 kg ou 10 kg). Le prix change bien en fonction du conditionnement mais le poids n'est pas calculé correctement au moment du calcul des frais de port.
Comment faire ?
Merci

**Comment by lmag** [comment]
Bonjour,

Avez-vous vérifié les réglages dans les modes de livraison ?

**Comment by lmag** [comment]
**Attention** à la version **2.0 ne sera pas compatible** avec les versions **1.X.Y** de [WPShop.fr](https://wpshop.fr/)
