### ISSUE TITLE
Problèmes sur PHP 7.2

### ISSUE THREAD

**Issue by acicovic** [Eoxia/WPshop-1.y.z#21]
Bonjour,

Nous avons besoin de mettre PHP à jour pour des raisons de sécurité. Quand nous mettons PHP à jour sur PHP 7.2 nous ne pouvons plus éditer et accéder à la page des produits. 

Quand nous essayons de voir le produit sur le site :

[16-Jan-2019 17:02:58 UTC] PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in wp-content/plugins/wpshop/includes/librairies/eav/attributes_set.class.php:977
Stack trace:
#0 wp-content/plugins/wpshop/includes/librairies/catalog/products.class.php(2532): wpshop_attributes_set::getAttributeSetDetails('1')
#1 wp-content/plugins/wpshop/includes/librairies/catalog/products.class.php(1570): wpshop_products::wpshop_variation(4165)
#2 wp-content/plugins/wpshop/includes/librairies/display/display.class.php(745): wpshop_products::product_complete_sheet_output('...', 4165)
#3 wp-includes/class-wp-hook.php(286): wpshop_display::products_page('...')
#4 wp-includes/plugin.php(203): WP_Hook->apply_filters('\...', Array)
#5 wp-includes/post-template.php(240): apply_filters('the_content', '.. in wp-content/plugins/wpshop/includes/librairies/eav/attributes_set.class.php on line 977

Quand nous essayons d’éditer un produit sur wp-admin :

[16-Jan-2019 17:06:24 UTC] PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in wp-content/plugins/wpshop/includes/librairies/eav/attributes_set.class.php:977
Stack trace:
#0 wp-content/plugins/wpshop/includes/librairies/eav/attributes.class.php(2243): wpshop_attributes_set::getAttributeSetDetails('1', ''valid','delete...')
#1 wp-content/plugins/wpshop/includes/librairies/catalog/products.class.php(250): wpshop_attributes::entities_attribute_box('1', 'wpshop_product', '4467')
#2 wp-includes/class-wp-hook.php(288): wpshop_products::add_meta_boxes('wpshop_product')
#3 wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 wp-admin/edit-form-advanced.php(334): do_action('add_meta_boxes', 'wpshop_product', Object(WP_Post))
#6 wp-admin/post.php(180): include('/home/...')
#7 {main in wp-content/plugins/wpshop/includes/librairies/eav/attributes_set.class.php on line 977

**Comment by lmag** [comment]
Bonjour,

Nous tournons sur PHP 7.1 pour le moment.
Nous allons bientôt publier la nouvelle version connectable facilement à un ERP (En standard Dolibarr).

Bien cordialement
