### ISSUE TITLE
Erreur quand modification dans Réglage / Boutique 

### ISSUE THREAD

**Issue by gugusman33** [Eoxia/WPshop-1.y.z#23]
Bonjour 

Des que j'enregistre une modification dans Réglage / Boutique j'ai cette erreur :

Fatal error: Uncaught Error: Cannot use string offset as an array in C:\xampp\htdocs\wordpress\wp-content\plugins\wpshop\includes\modules\wps_address\controller\wps_address_ctr.php:640 Stack trace: #0 C:\xampp\htdocs\wordpress\wp-content\plugins\wpshop\includes\modules\billing\billing.php(183): wps_address::get_addresss_form_fields_by_type('3') #1 C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(288): wpshop_modules_billing->wpshop_billing_address_validator(Array) #2 C:\xampp\htdocs\wordpress\wp-includes\plugin.php(208): WP_Hook->apply_filters(Array, Array) #3 C:\xampp\htdocs\wordpress\wp-includes\formatting.php(4709): apply_filters('sanitize_option...', Array, 'wpshop_billing_...', Array) #4 C:\xampp\htdocs\wordpress\wp-includes\option.php(306): sanitize_option('wpshop_billing_...', Array) #5 C:\xampp\htdocs\wordpress\wp-admin\options.php(283): update_option('wpshop_billing_...', Array) #6 {main} thrown in C:\xampp\htdocs\wordpress\wp-content\plugins\wpshop\includes\modules\wps_address\controller\wps_address_ctr.php on line 640

Je vous remercie d'avance si vous avez une solution ...

**Comment by eoxia-jimmy** [comment]
Bonjour,

WPshop 1 est incompatible PHP7+

Soit il faut passer en PHP 5.6, ou alors modifier la ligne 614 du fichier [wps_adress_ctr](https://github.com/Eoxia/wpshop/blob/master/includes/modules/wps_address/controller/wps_address_ctr.php#L614) 

de

`$all_addresses = '';`

vers 

`$all_addresses = array();`

**Comment by lmag** [comment]
La dernière livraison règle ce problème. 
Attention à la version 2.0 qui fera un saut de version. Cette version ne sera donc pas compatible avec la version 1.X.Y
