### ISSUE TITLE
erreur à l'installation avec php 7.4

### ISSUE THREAD

**Issue by redb** [Eoxia/WPshop-1.y.z#25]
Bonjour
Je suppose que l'erreur vient de la version php. Je vais tenter en php 7.3

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/clients/monsite/wp-content/plugins/wpshop-2.0.0/wpshop.php on line 30

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/php7.4/lib/php') in /home/clients/monsite/wp-content/plugins/wpshop-2.0.0/wpshop.php on line 30

**Comment by redb** [comment]
Je viens de voir que je n'ai pas installé Dolibarr. Je ressaye avec l'install complète

**Comment by eoxia-jimmy** [comment]
Bonjour,

il faut utiliser composer https://getcomposer.org/ et lancer la commande "composer install" à la racine du dossier wpshop2

Ou alors vous pouvez télécharger le zip de la branche wpshop2-f qui contient les vendor intégrés.

https://github.com/Eoxia/wpshop/tree/2.0.0-f

**Comment by redb** [comment]
merci, ça a parfaitement fonctionner avec la 2.0.0-f
