### ISSUE TITLE
Point 3 : ERP déconnecté

### ISSUE THREAD

**Issue by lmag** [Eoxia/WPshop-1.y.z#34]
-Procéder au paiement > demander un devis
-réinitiliser les mots de passes
-Redirection automatique
-Message de réglage wpshop que pour les admin
-Les anciens devis d'ou ils sortent ??
-Afficher les onglets Commandes et Facture avec un message "Les commandes et les factures ne sont pas encore disponible en ligne, vous pouvez contacter votre service commercial"
-Lien téléchargeable petit bugs /home/wpshop/public_html/sd_demo2/wp-content/plugins/wpshop/core/external/eo-framework/modules/wpeo-upload/shortcode/class-wpeo-upload-shortcode.php
-Erreur sur qui à passé la commande : https://demo2.wpshop.fr/wp-admin/admin.php?page=wps-proposal&id=66
-Erreur sur les listings :  29/04/20 15:54 DE000031 Notice: Undefined index: contact in /home/wpshop/public_html/sd_demo2/wp-content/plugins/wpshop/modules/proposals/view/item.view.php on line 40

**Comment by eoxia-jimmy** [comment]
C'est corrigé

**Comment by lmag** [comment]
-redirection automatique : https://demo2.wpshop.fr/wp-admin/
-réinitiliser les mots de passes affiner (le cycle email valider etc...)

**Comment by lmag** [comment]
-Afficher les onglets Commandes et Facture avec un message "Les commandes et les factures ne sont pas encore disponible en ligne, vous pouvez contacter votre service commercial"
Message ok en anglais à traduire
