### ISSUE TITLE
Point 5 : fonctionnalités bloquantes

### ISSUE THREAD

**Issue by lmag** [Eoxia/WPshop-1.y.z#36]
-Séparer devis et PR Front/Admin
-Tier manque metabox
-Devis manque metabox
-Checker les mails envoyés 
-traduction dolibarr

**Comment by eoxia-jimmy** [comment]
-Vérification des mails envoyés à toi de jouer @lmag 
-La traduction du module dolibarr-wpshop n'est pas une fonctionnalités bloquantes

**Comment by lmag** [comment]
-Checker les mails envoyés
--Fatal erreur lors de l'édition des mails
--Le bouton a un problème de CSS
--Voir le fonctionnement

**Comment by lmag** [comment]
Passer les Emails dans un post
Enregistrer les Emails envoyés dans ce post

**Comment by lmag** [comment]
Ok fait les modèles de mails seront proposés dans les prochaines versions
