### ISSUE TITLE
-Enlever la page backadmin (Réinitialiser de mot de passe, connexion wp-login)

### ISSUE THREAD

**Issue by lmag** [Eoxia/WPshop-1.y.z#50]
Quand tu es un client et roles abonné !
Rediriger : https://tonsuperwpshop/wp-admin/

**Comment by eoxia-amandine** [comment]
Plus de détails :
Quand tu arrives sur l'administration de WordPress (wp-admin, ou le nom donné à la place) et que tu as le rôle Abonné ou Client, tu es redirigé sur la page de gestion de ton compte en frontend.

**Comment by lmag** [comment]
OK controle
