### ISSUE TITLE
wps_signup_request redirige vers order_step=3 puis order_step=2

### ISSUE THREAD

**Issue by AVapps** [Eoxia/WPshop-1.y.z#6]
WPShop version 1.4.2.7 - Thème: SimplyOne

Le formulaire d'inscription (envoi de la requête ajax "action=wps_signup_request") redirige vers la page "Adresses" ("order_step=3") qui ensuite redirige vers la page d'identification ("order_step=2"). Le comportement précédent permettait au client d'entrer son adresse postale directement sans devoir se reconnecter (maintient sur la page "order_step=3").
Le client ne comprend pas pourquoi on lui redemande de taper son adresse e-mail et pense que l'inscription a échoué.

**Comment by eoxia-gael** [comment]
Les mises à jour récentes ont elles corrigé votre problème ?
